// Builds the no-build-step distribution of the client library from the same
// TypeScript the console and the apps import. There is one implementation of
// the protocol; this is the shape a page can reach with a <script> tag.
//
//   dist/nfc-client.js       classic script, globals on window
//   dist/nfc-client.esm.js   module build, for a bundler that wants one file
//   dist/*.d.ts              declarations, generated by tsc
//
// Committed to the repository, like webui/frontend/dist, so nothing downstream
// needs Node to consume it. Rebuild with `npm run build` here.

import { execFileSync } from "node:child_process";
import { rmSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entry = resolve(root, "src/index.ts");
const outdir = resolve(root, "dist");

rmSync(outdir, { recursive: true, force: true });

const shared = {
  entryPoints: [entry],
  bundle: true,
  target: "es2020",
  charset: "utf8",
  logLevel: "info",
};

// The classic script assigns its exports onto the page rather than returning
// them, so `new NFCClient(...)` works from an ordinary <script> — which is what
// client/test-client.html and a copy-and-paste integration do.
await esbuild.build({
  ...shared,
  format: "iife",
  globalName: "DaviNFC",
  footer: {
    js: "Object.assign(globalThis, DaviNFC);",
  },
  outfile: resolve(outdir, "nfc-client.js"),
});

await esbuild.build({
  ...shared,
  format: "esm",
  outfile: resolve(outdir, "nfc-client.esm.js"),
});

// Declarations come from tsc rather than esbuild, which does not emit them.
// react/ is left out: a classic script has no React to hook into, and a project
// that does imports the source through the package.
execFileSync(
  process.execPath,
  [
    resolve(root, "node_modules/typescript/bin/tsc"),
    "--ignoreConfig",
    "--declaration",
    "--emitDeclarationOnly",
    "--outDir",
    outdir,
    "--rootDir",
    resolve(root, "src"),
    "--target",
    "es2023",
    "--lib",
    "ES2023,DOM",
    "--module",
    "esnext",
    "--moduleResolution",
    "bundler",
    "--strict",
    "--skipLibCheck",
    entry,
  ],
  { cwd: root, stdio: "inherit" },
);
